### ISSUE TITLE
Invalid autolinks rendered from links with inline formatting

### ISSUE THREAD

**Issue by tvquizphd** [syntax-tree/mdast-util-to-markdown#10]
### Subject of the issue

Autolink formatting is great, but this utility appears to have an oversight when constructing autolinks from standard links with inline formatting for some or all of the link text.

### Your environment

*   **OS**: MacOS Sierra 10.12.6
*   **Packages**: mdast-util-to-markdown==0.6.1, remark==13.0.0
*   **Env**: [node==15.3.0, yarn==1.22.10, console] or [node==10.23.0, chrome==86.0.4240.111]

### Steps to reproduce

[Here's a CodeSandbox example](https://codesandbox.io/s/remark-debug-formatted-autolink-simple-g9p5w) containing a single link with formatted text correctly parsed to mdast with remark, then incorrectly serialized to markdown with `mdast-util-to-markdown`.

An example requiring minimal input is as follows:
```js
import remark from "remark";
import toMarkdown from "mdast-util-to-markdown";

const sourceMarkdown = "[**https://unifiedjs.com/**](https://unifiedjs.com/)";

const mdast = remark().parse(sourceMarkdown);
const contents = toMarkdown(mdast);
```

I use remark to convert `[**https://unifiedjs.com/**](https://unifiedjs.com/)` to an mdast that has a single paragraph with a single link whose structure can be represented (without "position") in JSON as follows:
```js
{
  "type": "link",
  "title": null,
  "url": "https://unifiedjs.com/",
  "children": [
    {
      "type": "strong",
      "children": [
        {
          "type": "text",
          "value": "https://unifiedjs.com/"
        }
      ]
    }
  ]
}
```

### Expected behavior

According to the [CommonMark spec](https://spec.commonmark.org/0.29/#example-512), link text may contain inline formatting. In general, this utility handles inline formatting of link text correctly. However, the specification does not allow for inline formatting of the autolink URI or email address.

As I see it, this utility would ideally not create autolinks from links with link text that contains inline formatting. Such links cannot be represented as autolinks without stripping the formatting and/or rendering the link invalid.

So, for a syntax-tree derived from the following markdown:
```md
[**https://unifiedjs.com/**](https://unifiedjs.com/)
```

this utility should serialize it to the same output markdown:
```md
[**https://unifiedjs.com/**](https://unifiedjs.com/)
```
 
This could perhaps be accomplished by an additional check in [`formatLinkAsAutolink`](https://github.com/syntax-tree/mdast-util-to-markdown/blob/7f8bd88871334fc60a04bdf99089df40f52cc4f5/lib/util/format-link-as-autolink.js) to ensure that the node has no inline formatting. Without knowing the correct convention for performing this check, I would suggest something conceptually similar to `node.children.every(child => child.type == 'text')`.
 
### Actual behavior

For a syntax-tree derived from the following markdown:
```md
[**https://unifiedjs.com/**](https://unifiedjs.com/)
```

this utility serializes it to an autolink with the following markdown:
```md
<**https://unifiedjs.com/**>
```

This resulting markdown contains an incorrect URI, equivalent to the following markdown:
```
[**https://unifiedjs.com/**](**https://unifiedjs.com/**)
```

**Comment by wooorm** [comment]
Thanks for the detailed report @tvquizphd! Fixed and released!
