### ISSUE TITLE
Support ordered list numbering.

### ISSUE THREAD

**Issue by tripodsan** [syntax-tree/mdast-util-to-markdown#11]
### Subject of the feature

It would be great to have a way to generate ordered lists, starting at any number, such as:

---
1. one
2. two

Some text...

3. Three
4. Four
---

### Problem

It's not possible to define the list starting number.

### Expected behavior

the simplest implementation could look for a `number` property on a `listItem` node.

**Comment by wooorm** [comment]
This should be possible? There's a 'start' prop on lists which is used when ordered: true?

**Comment by tripodsan** [comment]
aah:
https://github.com/syntax-tree/mdast-util-to-markdown/blob/f355cc6489517397a3ce6625975695058acaa69d/lib/handle/list-item.js#L18

never mind. thanks.
