### ISSUE TITLE
roundtripping inline code with list-like text results in list

### ISSUE THREAD

**Issue by ChristianMurphy** [syntax-tree/mdast-util-to-markdown#13]
### Subject of the issue

```markdown
`
-`
```

is stringified as:

```markdown
`
- `
```

which changes the structure

### Your environment

*   **OS**: Ubuntu
*   **Packages**: mdast-util-to-markdown 0.6.2
*   **Env**: node v15.5.1, npm 7.3.0

### Steps to reproduce

parse

```markdown
`
-`
```

which has the structure

```json
{
    "type": "root",
    "children": [
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "inlineCode"
                }
            ]
        }
    ]
}
```

and stringify it:

```markdown
`
- `
```

the resulting markdown has a different structure than the original
```json
{
    "type": "root",
    "children": [
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "text"
                }
            ]
        },
        {
            "type": "list",
            "ordered": false,
            "start": null,
            "children": [
                {
                    "type": "listItem",
                    "checked": null,
                    "children": [
                        {
                            "type": "paragraph",
                            "children": [
                                {
                                    "type": "text"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```

:notebook: comparing how the two pieces of markdown text are being parsed with https://spec.commonmark.org/dingus it appears in both cases it is parsed as expected.

### Expected behavior

structure is the same

### Actual behavior

structure is different

**Comment by wooorm** [comment]
Hmm. Complex.

Inline code is rather fragile when it comes to block markers after newlines:

```
`
# `

`
1. `

`
1) `

`
+ `

`
- `

`
* `

`
<div `

`
= `

`
> `
```

Yields:

`
# `

`
1. `

`
1) `

`
+ `

`
- `

`
* `

`
<div `

`
= `

`
> `

**Comment by wooorm** [comment]
Maybe, when a newline is found, we can use the [unsafe patterns](https://github.com/syntax-tree/mdast-util-to-markdown/blob/f355cc6489517397a3ce6625975695058acaa69d/lib/unsafe.js#L38)’s `atBreak`s, and use a space instead of a line endings?
