### ISSUE TITLE
roundtripping mixed html and text results in html

### ISSUE THREAD

**Issue by ChristianMurphy** [syntax-tree/mdast-util-to-markdown#15]
### Subject of the issue

```markdown
any text
    <div>more text
```

is stringified as:

```markdown
any text
<div>more text
```

which changes the structure

### Your environment

*   **OS**: Ubuntu
*   **Packages**: mdast-util-to-markdown 0.6.2
*   **Env**: node v15.5.1, npm 7.3.0

### Steps to reproduce

parse

```markdown
any text
    <div>more text
```

which has the structure

```json
{
    "type": "root",
    "children": [
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "text"
                },
                {
                    "type": "html"
                },
                {
                    "type": "text"
                }
            ]
        }
    ]
}

```

and stringify it:

```markdown
any text
<div>more text
```

the resulting markdown has a different structure than the original
```json
{
    "type": "root",
    "children": [
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "text"
                }
            ]
        },
        {
            "type": "html"
        }
    ]
}
```

:notebook: comparing how the two pieces of markdown text are being parsed with https://spec.commonmark.org/dingus it appears in both cases it is parsed as expected.

### Expected behavior

structure is the same

### Actual behavior

structure is different

**Comment by wooorm** [comment]
A similar case would probably be:

````markdown
a
    ```b
    ```

a
```b
```
````

(as in, the overlap between things that could turn into blocks, and have a different meaning when found inline).

Escaping wouldn’t solve this, but perhaps the eol can be swapped for a space

**Comment by wooorm** [comment]
the code case seems to be prevented by https://github.com/syntax-tree/mdast-util-to-markdown/commit/cf7cf8f1fbe0b54332a6708e9bd956e14c2fafda though, so I’m guessing this only happens to code

**Comment by wooorm** [comment]
Here are some more examples for all HTML cases (https://spec.commonmark.org/0.29/#html-blocks) that should have these problems:

```markdown
c1
    <script></script>

c1
<script></script>

c2
    <!---->

c2
<!---->

c3
    <??>

c3
<??>

c4
    <!A b>

c4
<!A b>

c5
    <![CDATA[]]>

c5
<![CDATA[]]>

c6
    <div>

c6
<div>

c7 (cannot interrupt a paragraph)
```
