### ISSUE TITLE
round tripping multiline header results in single line header

### ISSUE THREAD

**Issue by ChristianMurphy** [syntax-tree/mdast-util-to-markdown#17]
### Subject of the issue

```markdown
text  
text-
-
text
```

is stringified as:

```markdown
## text\
text-

text
```

which changes the structure

### Your environment

*   **OS**: Ubuntu
*   **Packages**: mdast-util-to-markdown 0.6.4
*   **Env**: node v15.5.1, npm 7.3.0

### Steps to reproduce

parse

```markdown
text  
text-
-
text
```

which has the structure

```json
{
    "type": "root",
    "children": [
        {
            "type": "heading",
            "depth": 2,
            "children": [
                {
                    "type": "text"
                },
                {
                    "type": "break"
                },
                {
                    "type": "text"
                }
            ]
        },
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "text"
                }
            ]
        }
    ]
}
```

and stringify it:

```markdown
## text\
text-

text
```

the resulting markdown has a different structure than the original
```json
{
    "type": "root",
    "children": [
        {
            "type": "heading",
            "depth": 2,
            "children": [
                {
                    "type": "text"
                }
            ]
        },
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "text"
                }
            ]
        },
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "text"
                }
            ]
        }
    ]
}
```

:notebook: comparing how the two pieces of markdown text are being parsed with https://spec.commonmark.org/dingus it appears in both cases it is parsed as expected.

### Expected behavior

structure is the same

### Actual behavior

structure is different

**Comment by wooorm** [comment]
This is another case where I think the AST should change: the style of headings is ATX by default: breaks can’t occur in ATX headings, going `'a  \nb\n='` (or `'a\\\nb\n='`) to `# a b` makes the most sense to me
