### ISSUE TITLE
roundtripping lists adds html node between

### ISSUE THREAD

**Issue by ChristianMurphy** [syntax-tree/mdast-util-to-markdown#18]
### Subject of the issue

```markdown
- a
* b
```

is stringified as:

```markdown
*   a

<!---->

*   b
```

which changes the structure

### Your environment

*   **OS**: Ubuntu
*   **Packages**: mdast-util-to-markdown 0.6.4
*   **Env**: node v15.5.1, npm 7.3.0

### Steps to reproduce

parse

```markdown
- a
* b
```

which has the structure

```json
{
    "type": "root",
    "children": [
        {
            "type": "list",
            "ordered": false,
            "start": null,
            "children": [
                {
                    "type": "listItem",
                    "checked": null,
                    "children": [
                        {
                            "type": "paragraph",
                            "children": [
                                {
                                    "type": "text"
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "type": "list",
            "ordered": false,
            "start": null,
            "children": [
                {
                    "type": "listItem",
                    "checked": null,
                    "children": [
                        {
                            "type": "paragraph",
                            "children": [
                                {
                                    "type": "text"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```

and stringify it:

```markdown
*   a

<!---->

*   b
```

the resulting markdown has a different structure than the original
```json
{
    "type": "root",
    "children": [
        {
            "type": "list",
            "ordered": false,
            "start": null,
            "children": [
                {
                    "type": "listItem",
                    "checked": null,
                    "children": [
                        {
                            "type": "paragraph",
                            "children": [
                                {
                                    "type": "text"
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "type": "html"
        },
        {
            "type": "list",
            "ordered": false,
            "start": null,
            "children": [
                {
                    "type": "listItem",
                    "checked": null,
                    "children": [
                        {
                            "type": "paragraph",
                            "children": [
                                {
                                    "type": "text"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```

:notebook: comparing how the two pieces of markdown text are being parsed with https://spec.commonmark.org/dingus it appears in both cases it is parsed as expected.

### Expected behavior

structure is the same

### Actual behavior

structure is different

**Comment by ChristianMurphy** [comment]
related to https://github.com/remarkjs/remark/issues/565

**Comment by wooorm** [comment]
this is expected. there’s no way around it 🤷‍♂️

**Comment by ChristianMurphy** [comment]
> there’s no way around it

:raised_eyebrow: there is a way around it, list bullet types can be interleaved, starting with `*` going to `-` on to `+`
It may be more complex than we want to implement, but it is possible.

**Comment by ChristianMurphy** [comment]
The AST does have enough information, logically it could check:
* if the next (or previous) sibling of a list is another list then increment the list character used
* otherwise use `*`

**Comment by wooorm** [comment]
Roundtripping is one thing btw, but ASTs also come from other places, e.g., from orgmode, html, but also when injected by plugins from other sources. In those cases, I think making a consistent document is more important than making something that can roundtrip

**Comment by ChristianMurphy** [comment]
I'm not sure I get the consistency argument here.
I can generate the above AST with two lists through a plugin, manually, and any number of other ways.
In all cases `mdast-util-to-markdown` inserts an AST node which wasn't there before.

I get the desire for a consistently structured document and that the pattern of lists next to lists may not be ideal.
But that decision feels like a decision which is configurable, or possibly split into a remark plugin or remark-lint rule, rather than being imposed by the stringifier.

**Comment by wooorm** [comment]
This is becoming more complex that I thought:

```
* ---
- a
+ b
```

Naively solving this issue would use `bullet` for 1 and 3, and `otherBullet` for 2.
But because of https://github.com/syntax-tree/mdast-util-to-markdown/issues/6, `otherBullet` is used for 1 😬

https://github.com/syntax-tree/mdast-util-to-markdown/blob/f93dfff3dbaf7b6b28f4b17ac73c62043ad0fd71/test/index.js#L2558-L2565
