### ISSUE TITLE
roundtripping escapes before emphasis causes emphasis to be lost

### ISSUE THREAD

**Issue by ChristianMurphy** [syntax-tree/mdast-util-to-markdown#19]
### Subject of the issue

```markdown
\\\\*text*
```

is stringified as:

```markdown
\\\*text*
```

which changes the structure

### Your environment

*   **OS**: Ubuntu
*   **Packages**: mdast-util-to-markdown 0.6.4
*   **Env**: node v15.5.1, npm 7.3.0

### Steps to reproduce

parse

```markdown
\\\\*text*
```

which has the structure

```json
{
    "type": "root",
    "children": [
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "text"
                },
                {
                    "type": "emphasis",
                    "children": [
                        {
                            "type": "text"
                        }
                    ]
                }
            ]
        }
    ]
}
```

and stringify it:

```markdown
\\\*text*
```

the resulting markdown has a different structure than the original
```json
{
    "type": "root",
    "children": [
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "text"
                }
            ]
        }
    ]
}

```

:notebook: comparing how the two pieces of markdown text are being parsed with https://spec.commonmark.org/dingus it appears in both cases it is parsed as expected.

### Expected behavior

structure is the same

### Actual behavior

structure is different

**Comment by wooorm** [comment]
Wasn't that fixed just now? 🤔

**Comment by ChristianMurphy** [comment]
https://github.com/syntax-tree/mdast-util-to-markdown/issues/14 was emphasis becoming text, this is text becoming emphasis

**Comment by ChristianMurphy** [comment]
This can also happen with code

````markdown
\\\\`code`
````

and with HTML

````markdown
\\\\<div>
````
