### ISSUE TITLE
Please support delete (strike-through)

### ISSUE THREAD

**Issue by bartv2** [syntax-tree/mdast-util-to-markdown#2]
### Subject of the feature

I noticed that https://github.com/syntax-tree/mdast#delete is missing

### Expected behavior

Output like strong but with ~

### Alternatives

I considered writing my own handler, but it is such a basic thing, and it should just be supported by the package. 

Thanks for the package BTW, released/created just when i was looking for something like this.

**Comment by ChristianMurphy** [comment]
This only supports [commonmark](https://commonmark.org/) out of the box, strike through is a [GFM syntax feature](https://github.github.com/gfm/).
Which can be added through a plugin https://github.com/syntax-tree/mdast-util-gfm-strikethrough
