### ISSUE TITLE
roundtripping escape before break causes break to disappear

### ISSUE THREAD

**Issue by ChristianMurphy** [syntax-tree/mdast-util-to-markdown#22]
### Subject of the issue

```markdown
text\\\\\
text
```

is stringified as:

```markdown
text\\\\
text
```

which changes the structure

### Your environment

*   **OS**: Ubuntu
*   **Packages**: mdast-util-to-markdown 0.6.4
*   **Env**: node v15.5.1, npm 7.3.0

### Steps to reproduce

parse

```markdown
text\\\\\
text
```

which has the structure

```json
{
    "type": "root",
    "children": [
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "text"
                },
                {
                    "type": "break"
                },
                {
                    "type": "text"
                }
            ]
        }
    ]
}
```

and stringify it:

```markdown
text\\\\
text
```

the resulting markdown has a different structure than the original
```json
{
    "type": "root",
    "children": [
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "text"
                }
            ]
        }
    ]
}
```

:notebook: comparing how the two pieces of markdown text are being parsed with https://spec.commonmark.org/dingus it appears in both cases it is parsed as expected.

### Expected behavior

structure is the same

### Actual behavior

structure is different

**Comment by ChristianMurphy** [comment]
related to #19 but the sensitivity to a number in the protocol makes me think it _may_ have a different root cause.

**Comment by wooorm** [comment]
Yup, was GH-19.
