### ISSUE TITLE
roundtripping causes implicitly closed code block to disappear

### ISSUE THREAD

**Issue by ChristianMurphy** [syntax-tree/mdast-util-to-markdown#24]
### Subject of the issue

````markdown
```
	
````

:notebook: note the tab at the end of the second line, it is significant

is stringified as:

````markdown
    	
````

which changes the structure

### Your environment

*   **OS**: Ubuntu
*   **Packages**: mdast-util-to-markdown 0.6.4
*   **Env**: node v15.5.1, npm 7.3.0

### Steps to reproduce

parse

````markdown
```
	
````

which has the structure

```json
{
    "type": "root",
    "children": [
        {
            "type": "code"
        }
    ]
}
```

and stringify it:

```markdown
    	
```

the resulting markdown has a different structure than the original
```json
{
    "type": "root",
    "children": []
}

```

:notebook: comparing how the two pieces of markdown text are being parsed with https://spec.commonmark.org/dingus it appears in both cases it is parsed as expected.

### Expected behavior

structure is the same

### Actual behavior

structure is different

**Comment by wooorm** [comment]
It’s not about closing, it’s about blank lines in fenced code possibly existing, but not in indented code
