### ISSUE TITLE
Roundtripping multiline SETEXT header collapses to single line

### ISSUE THREAD

**Issue by ChristianMurphy** [syntax-tree/mdast-util-to-markdown#26]
### Subject of the issue

````markdown
```a`
`
a
=
````

is stringified as:

````markdown
# \`\`\`a`
`&#xA;a
````

which changes the structure

### Your environment

*   **OS**: Ubuntu
*   **Packages**: mdast-util-to-markdown 0.6.5
*   **Env**: node v15.5.1, npm 7.3.0

### Steps to reproduce

parse

````markdown
```a`
`
a
=
````

which has the structure

```json
{
    "type": "root",
    "children": [
        {
            "type": "heading",
            "depth": 1,
            "children": [
                {
                    "type": "text"
                },
                {
                    "type": "inlineCode"
                },
                {
                    "type": "text"
                }
            ]
        }
    ]
}
```

and stringify it:

````markdown
# \`\`\`a`
`&#xA;a
````

the resulting markdown has a different structure than the original
```json
{
    "type": "root",
    "children": [
        {
            "type": "heading",
            "depth": 1,
            "children": [
                {
                    "type": "text"
                }
            ]
        },
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "text"
                }
            ]
        }
    ]
}
```

:notebook: comparing how the two pieces of markdown text are being parsed with https://spec.commonmark.org/dingus it appears in both cases it is parsed as expected.

### Expected behavior

structure is the same

### Actual behavior

structure is different

**Comment by ChristianMurphy** [comment]
A smaller example without inline code

````markdown
text
\\
text
-
````

**Comment by wooorm** [comment]
Yes, I just added this: https://github.com/syntax-tree/mdast-util-to-markdown/issues/17#issuecomment-773910736

**Comment by wooorm** [comment]
Oh no I guess this is different: but I still think it makes sense for a heading of `a\nb\n=`, when serializing as ATX, to be using a space

**Comment by ChristianMurphy** [comment]
one more SETEXT related edge case

````markdown
<tag
attr>
=
````
