### ISSUE TITLE
Nested MDX and indentation

### ISSUE THREAD

**Issue by revolunet** [syntax-tree/mdast-util-to-markdown#28]
### Nested MDX and indentation

Hi, i'm not sure where exactly to land that issue; looks like when parsing some MDX containing nested MDX components, the output from `toMarkdown` is reindented. 

Input to `from-markdown` :

```md
<Tab title="some-tab">
<Tab>

Some **blabla**

-   Item 2
</Tab>
</Tab>
```

Output from `to-markdown` :

```md
<Tab title="some-tab">
  <Tab>
    Some **blabla**

    - Item 2
  </Tab>
</Tab>
```

That sounds pretty, but is what is expected on the MDX spec ?

Looks like this is not compatible with markdown as it interprets the block in the nested `Tab` as a `code` block.

I've tried with remark-parse + rehype-react to re-render this output to HTML with no luck as it renders the block as `code`.

### Steps to reproduce

This sandbox demonstrates the issue : https://codesandbox.io/s/mdx-inputoutput-react-renderer-56giy?file=/src/App.js

### Expected behavior

The indented tree should be fully rendered 

### Actual behavior

The nested tags code is rendered as `code` block

**Comment by wooorm** [comment]
> That sounds pretty, but is what is expected on the MDX spec ?

Yes, people expected to write their JSX w/ indentation, so a) we need to parse that, and b) we need to serialize that too

> Looks like this is not compatible with markdown as it interprets the block in the nested Tab as a code block.

That is correct. More documented here: https://github.com/wooorm/xdm#caveats.

markdown !== mdx !== markdown; they’re different formats.

**Comment by revolunet** [comment]
Ok, makes sense to me, thanks! but how to parse it correctly after parse/seralize for rehype-react ?

**Comment by wooorm** [comment]
I’m a bit unclear about where you’re coming from.

You are now parsing MDX and serializing it. Well, you can use an MDX parser to turn it into react components. E.g., these steps: https://github.com/wooorm/xdm/blob/978f5ee081664a57cb3d6246f01e93831e3cc331/lib/core.js#L67-L82 are done by xdm.

Or you go with plain-vanilla markdown: use remark-parse (+ remark-directives?) -> remark-rehype -> rehype-react.

There are many ways to go with unified, but it all depends on what you want to do, and I’m not 100% about what that is

**Comment by revolunet** [comment]
The [sandbox](https://codesandbox.io/s/mdx-inputoutput-react-renderer-56giy?file=/src/Mdx.js) shows the full process i'm trying to achieve : parse and reserialize process (this is where i'll do some find and replace) then load again the result with a `Mdx` component that use unified, remark-parse, remark2rehype, rehype2react then render

I'll play with your XDM example, thanks !

**Comment by revolunet** [comment]
Ive tried with XDM directly, which has a very simpler API but i get the same result, looks like indented content inside MDX components is rendered as `<code>` 🤔

**Comment by wooorm** [comment]
Running this in a cloned `xdm` repo:

```js
import {compileSync} from './index.js'

var input = `<Tab title="some-tab">
  <Tab>
    Some **blabla**

    - Item 2
  </Tab>
</Tab>`

console.log(String(compileSync(input, {jsx: true})))
```

(`jsx: true` to make it more clear what’s going on)

Yields:

```js
/* … */
function MDXContent(_props) {
  /* … */
  const _content = <><Tab title="some-tab"><Tab><_components.p>{"Some "}<_components.strong>{"blabla"}</_components.strong></_components.p><_components.ul>{"\n"}<_components.li>{"Item 2"}</_components.li>{"\n"}</_components.ul></Tab></Tab></>;
  return MDXLayout ? <MDXLayout {..._props}>{_content}</MDXLayout> : _content;
}
export default MDXContent;
```

That looks like what you want?

**Comment by wooorm** [comment]
weird, I pasted `parsedMarkdown` from your code into `input`, so I’m getting this locally. But your demo indeed renders differently.

**Comment by wooorm** [comment]
Are some versions old? I don’t know how to do an `npm install` on codesandbox to reinstall things

**Comment by wooorm** [comment]
Removing a bunch of stuff, and it worked 🤷‍♂️

https://codesandbox.io/s/mdx-inputoutput-react-renderer-forked-96m1l?file=/package.json

It might be some deduping that codesandbox was doing, so that maybe an old remark or so was used? 🤷‍♂️🤷‍♂️ No clue!

**Comment by revolunet** [comment]
> That looks like what you want?

yes that looks perfect ! 👍 

> Removing a bunch of stuff, and it worked 🤷‍♂️

Ho, awesome thank a lot for helping me here, while i explore the unified ecosystem since a while i'm still bad at identifying all the involved parts and best practices. Is there any active community chat/gitter ?

Weird, looks like the problem was due to all the dependencies i tried on my way. thanks man !

**Comment by revolunet** [comment]
When importing that exmeple into next.js

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/juju/xxx/node_modules/xdm/index.js

require() of ES modules is not supported.

require() of /Users/juju/xxx/node_modules/xdm/index.js from /Users/juju/xxx/.next/server/pages/mdx.js is an ES module 
file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that 
package scope as ES modules.

Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from 
/Users/juju/xxx/node_modules/xdm/package.json.
```

**Comment by wooorm** [comment]
See install instructions: https://github.com/wooorm/xdm#install.
If you’re in CJS, use `import('xdm'). Otherwise, when in ESM, use `import 'xdm'`.

Ref. https://twitter.com/sindresorhus/status/1349294527350149121

**Comment by revolunet** [comment]
i'm using `import { evaluateSync } from "xdm";` is there another syntax ?

**Comment by wooorm** [comment]
That should work. But it doesn’t work if you are in CJS.
Your file has requires, too, right? They can’t co-exist.

**Comment by wooorm** [comment]
Maybe the simplest is to try and `import('xdm').then(xdm => { ... })` if you’re in CJS?

**Comment by revolunet** [comment]
i dont have require in the file.

Its working like that but i have to use `setState` due to async loading

```js
import React, { useState } from "react";
import * as runtime from "react/jsx-runtime.js";
import { Tab } from "../contributions/rehypeToReact";

const Mdx = ({ markdown }) => {
  const [loaded, setLoaded] = useState(false);
  import("xdm").then((xdm) => {
    setLoaded(xdm);
  });

  if (!loaded) {
    return null;
  }

  const wrappedMarkdown = markdown.replace(
    /(<Content [^>]+><\/Content>)/,
    "<div>$1</div>"
  );

  const { default: Content } = loaded.evaluateSync(wrappedMarkdown, {
    ...runtime,
  });

  return <Content components={{ Tab }} />;
};

export default Mdx;
```

Is there a way to prevent `Error: Component `xxx` was not imported, exported, or given` when some tag is not found ?

**Comment by wooorm** [comment]
> Is there a way to prevent Error: Component xxx was not imported, exported, or given when some tag is not found ?

How would you propose undefined components be handled? React will also crash on undefined 🤷‍♂️

**Comment by revolunet** [comment]
Fallback to `React.Fragment`, or `div`

**Comment by wooorm** [comment]
`div` can’t work, because sometimes components are “inline”.

Fragment... I’m just not sure why you’d have components in your `.mdx` file that aren’t defined. I don’t get why it’d be a good idea to do something differently than react et al do it.

Btw, “tags” are fine: `<foooo>` renders w/o an error. Explicit components, such as `<Foo>` and `<foo.bar>` and so throw this error.

**Comment by revolunet** [comment]
ok, i was wondering about cases where you parse MDX that can include new or unknown components. should it fail or should it only "drop" related nodes.

Just a question though, i know my MDX :)

**Comment by wooorm** [comment]
> ok, i was wondering about cases where you parse MDX that can include new or unknown components. should it fail or should it only "drop" related nodes.

It is unknown at compile time which components are known or not. So at compile time we basically do this:

```js
var Foo = givenComponents.Foo || () => throw new Error('Foo was not given!')

<Foo />
```

This is needed because `<Foo>`, with the uppercase, compiles to an identifier:

```js
var Foo = givenComponents.Foo || () => throw new Error('Foo was not given!')

_jsx(Foo, {children: undefined})
```

And we must make sure that identifier is defined.

Then at runtime, either the component is given, or an error is thrown.

We *could* return a fragment instead. But then: maybe the component hijacks children? Or does not render children?
I think it’s good to instead crash as fast as possible: the content was expecting something, but it’s not given

**Comment by revolunet** [comment]
Looks like [we cannot use Next.js for ESM modules yet](https://github.com/vercel/next.js/issues/9607) but its in-progress.

Meanwhile, one can use [next-transpile-modules](https://github.com/martpie/next-transpile-modules) and add `xdm` and  `unist-util-position-from-estree` to its next.config.js configuration

**Comment by wooorm** [comment]
Hmmm. Thanks for checking that out!

xdm was a tiny test in the waters. But I’ve just started moving all my projects over. Low-level first, and upwards from there. Webpack is also having problems.... Complex time!

**Comment by wooorm** [comment]
And if you use this to load complete files? https://github.com/wooorm/xdm#next

**Comment by revolunet** [comment]
Well i dont use files, the MDX comes from a database, not sure i can use a loader there ?

**Comment by wooorm** [comment]
Indeed you can’t.

`next-mdx-remote` is what lots of folks use in the Next space. They’re working on an xdm branch: https://github.com/hashicorp/next-mdx-remote/tree/brk.feat/xdm/src

**Comment by revolunet** [comment]
At the end i think i won't be able to use xdm in Next.js because looks like it needs the `script-src: unsafe-eval` CSP directive;

i think i have to give another try to "plain-vanilla markdown: use remark-parse (+ remark-directives?) -> remark-rehype -> rehype-react.". If i understand correctly, it should be able to handle indentation in nested MDX correctly

**Comment by revolunet** [comment]
I've tried various combinations using the unified and mdast-utils tools to render the MDX correctly but with no luck; for some reason, the indented MDX still get rendered as code; I dont understand if it comes from the remark-parser or remark-to-rehype or somewhere else 🤔 any idea ?

https://codesandbox.io/s/mdx-react-renderer-j0mih?file=/src/Mdx.js

**Comment by wooorm** [comment]
@revolunet You’re trying to bridge two formats which are completely different.

In your example there, MDX is not added. `remark-parse` does not have a `fromMarkdownExtensions` option.
So, the rest of the pipeline is “just” a vanilla markdown -> html pipeline.
If you’d “fix” that ([see here](https://github.com/remarkjs/remark/blob/main/packages/remark-parse/index.js)), everything would crash, because remark-rehype, rehype-raw, and rehype-react have no clue what to do with JSX elements.

And, well, what you’re getting now is how HTML works in markdown: https://spec.commonmark.org/dingus/?text=%3CTab%20title%3D%22some-tab%22%3E%0ASome%20blabla%0A%0A-%20%20%20Item%201%0A%20%20%20%20-%20%20%20Item%201-1%0A%20%20%20%20-%20%20%20Item%201-2%0A%0A%20%20%3CTab%3E%0A%0A%20%20%20%20Some%20**blabla**%0A%0A%20%20%20%20-%20%20%20Item%202%0A%0A%20%20%20%20%20%20%20%20ou%0A%0A%20%20%20%20-%20%20%20Item%203%0A%0A%20%20%20%20More%20blabla%0A%0A%20%20%3C%2FTab%3E%0A%3C%2FTab%3E%0A.

xdm is jumping through a lot of hoops to handle JSX in markdown: https://github.com/wooorm/xdm/blob/978f5ee081664a57cb3d6246f01e93831e3cc331/lib/core.js#L74-L81.

I thought you were going with vanilla markdown + directives?

**Comment by wooorm** [comment]
Do you prefer the JSX syntax (which comes with JS expressions and such + no indents)? Is the HTML syntax not enough for what you want?

**Comment by revolunet** [comment]
My hope is to render MDX (with nested components) with React. i wanted to use remark-parse then rehype-react to achieve this but looks like im on the wrong path :/ 

My MDX doesnt have any import/export, just markdown using components inside it

As expected, the output from your dingus link treats the nested `Tab` content as a `code` block. which is as you say how HTML works in markdown, but not why i'm looking for

Should i try to reproduce whats going on in your XDM link ?

**Comment by wooorm** [comment]
> Should i try to reproduce whats going on in your XDM link ?

That path leads to the problem you had before, that `eval` wasn’t allowed.
The reason is: JSX/MDX is *JavaScript*, it’s “programming” compared to where markdown/HTML are “content” (not the best words, but the best I can think of). So the JSX needs to be evaluated somewhere.

**Comment by wooorm** [comment]
```js
unified()
  .use(remarkParse, {
    extensions: [
      // Support tokenizing mdx, *agnostic* to JS.
      // Expressions still do something, which you’ll need to handle
      require('micromark-extension-mdx')
    ],
    mdastExtensions: [
      // Support those tokens and turn them into AST nodes.
      require('mdast-util-mdx')
    ]
  })
  .use(remark2rehype, {
    // Pass those JSX nodes through from mdast to hast.
    // None of the rehype plugins understand them though, so several steps will
    // crash if we don’t handle those nodes.
    passThrough: ['...']
  })
  // Now you need to handle those things.
  // `rehype-react` understands hast nodes and not your components.
  // So you’d need to DIY it to support them.
  .use(yourForkOfRehypeReact)
```

**Comment by wooorm** [comment]
Or alternatively:

```js
unified()
  .use(remarkParse, {
    // Same as above.
  })
  .use(remark2rehype, {
    // Same as above.
  })
  // DIY
  .use(yourPluginToTurnJsxAndExpressionsIntoHastElements)
  // Now it’s normal hast.
  .use(rehypeReact)
```

**Comment by revolunet** [comment]
> JSX/MDX is JavaScript where markdown/HTML are “content” 

crystal clear thanks !

My initial workaround was to use rehype-react over the MDX content which was treated as MD+HTML, and rehype2react could then replace a `Tab` (which had been converted to HTML `tab`) with a React component and it worked correctly.

Now that i preprocess the MDX and use `toMarkdown`, it creates a perfectly indented MDX, and rehype? now produce `code` blocks instead of nesting tags. maybe i can find a solution to "fix" the indentation at tree level so i can keep a md/html pipeline without the `eval` 🤔 

Thanks for the examples

**Comment by revolunet** [comment]
Maybe a silly idea, but do you have an idea on how to transform this string :

```
<Tab title="some-tab">
  <Tab>
    Some **blabla**
      <Tab>
        Some **blabla**
      </Tab>
  </Tab>
</Tab>
```

into this one ?

```
<Tab title="some-tab">
<Tab>
<Tab>
  Some **blabla**
 </Tab>
</Tab>
</Tab>
```

all the tags should be reindented to column 0.

this could make rehype-react compatible with nested MDX

**Comment by revolunet** [comment]
Yeah its weird indeed, im reindenting the MDX so it can be parseable by rehype-recact. works currently but it is kind of fragile as we expect a correct markdown input. anyway thanks for your help along the way !

**Comment by wooorm** [comment]
Welp, took a while, but I finally fixed those find-and-replace bugs! https://github.com/syntax-tree/hast-util-find-and-replace/releases/tag/4.0.0 and https://github.com/syntax-tree/mdast-util-find-and-replace/releases/tag/2.0.0!
