### ISSUE TITLE
Is there any way to preserve the final trailing new line style?

### ISSUE THREAD

**Issue by JounQin** [syntax-tree/mdast-util-to-markdown#29]
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

### Subject

As title

### Problem

I want to preserve the final trailing whitespace.

For example, when linting markdown in js template:

```js
const markdown = `## This is the markdown in markdown content` // will be extracted to be linted
```

I don't want to add the final trailing whitespace automatically.

It should as same as the source what means it should:

1. when the source has trailing new lines, normalize them with one single `\n`
2. When the source do not have trailing new lines, do not add `\n`

### Solution

Add an option like `trailingNewLine: 'auto'`(`true` for always `\n`, `false` for no `\n`)

### Alternatives

N/A

**Comment by wooorm** [comment]
> I don't want to add the final trailing whitespace automatically.

Files should have a final line feed: https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline.

---

`mdast-util-to-markdown` has no knowledge of input. There’s no way to know this — it’s an AST, not a CST. See also https://github.com/syntax-tree/mdast-util-to-markdown/issues/3#issuecomment-700162630.

I am assuming that you might know whether the original file had a final line feed, so you might be able to add that back (or not).

**Comment by JounQin** [comment]
> I am assuming that you might know whether the original file had a final line feed, so you might be able to add that back (or not).

Yeah, that's what I'm doing. I'm just concerning a lint rule would report the final line issue and fix it automatically, then I can't determine if the new line is added by the rule, or `remark-stringify`.

**Comment by wooorm** [comment]
Can you turn it off? Like so: https://github.com/eslint/eslint-plugin-markdown/blob/58729d5de22dbbafe52d7b8f8f0d84f2e17770e4/lib/index.js#L33-L35

**Comment by JounQin** [comment]
Of course I can add it into a config preset, but it would be better to "fix" it. 😂

No worry if you think it's out of scope of this package.
