### ISSUE TITLE
Consistency between original and produced

### ISSUE THREAD

**Issue by RichardFevrier** [syntax-tree/mdast-util-to-markdown#3]
Hello everybody 👋 thank you for your amazing work !

### Keep consistency

After parsing some markdown (that we do not control, like a user input) with `mdast-util-from-markdown` we are able to obtain a mdtree.
But if we want to reverse this process by using `mdast-util-to-markdown` on the previous tree, the output will be modified even if we are not specifying any option.

Ex: 

Input:
```
# Title

## Subtitle

- elem1

- elem2

- elem3
```

```
const mdtree = md2mdast(markdown);
const markdown2 = mdast2md(mdtree);
```

Output:
```
# Title

## Subtitle

*   elem1

*   elem2

*   elem3
```

### Problem

How to keep consistency between input and output ?

**Comment by ChristianMurphy** [comment]
@RichardFevrier something to be aware of MDAST, is an [Abstract Syntax Tree](https://en.wikipedia.org/wiki/Abstract_syntax_tree).
The abstract part means that it loses some syntactic details, preserving those details are a non-goal for an AST (see a similar discussion at remark https://github.com/remarkjs/remark/issues/518#issuecomment-662878217)

To preserve exact detail, a [Concrete Syntax Tree (CST)](https://en.wikipedia.org/wiki/Parse_tree) is needed.
There has been some discussion of creating MDCST to support a use case like this, and [micromark](https://github.com/micromark/micromark#intro) would enable the parse side of this.
The CST part would be a new project.

**Comment by RichardFevrier** [comment]
@ChristianMurphy thank you for your answer!

Just one more question, do you know if there is a plan to produce this csttree like `mdast-util-from-markdown` does for the mdtree, and having also the same reverse possibility like `mdast-util-to-markdown` ?

**Comment by ChristianMurphy** [comment]
The details aren't finalized by any means.
Speculatively, yes. There likely would be a utility to go from markdown text to a CST, and another to go from CST to markdown text.
