### ISSUE TITLE
Can not handle "delete" type

### ISSUE THREAD

**Issue by ivanbanov** [syntax-tree/mdast-util-to-markdown#38]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.0.1

### Steps to reproduce

https://codesandbox.io/s/friendly-leftpad-1lcrc?file=/src/index.js

### Expected behavior

The same behavior that `strong` or `emphasis` have

### Actual behavior

![image](https://user-images.githubusercontent.com/2953018/125495089-1a94d7d8-14b6-45bd-93a6-0dd36683a868.png)

**Comment by wooorm** [comment]
https://github.com/syntax-tree/mdast-util-gfm-strikethrough
