### ISSUE TITLE
User defined handlers erases any extension defined handler

### ISSUE THREAD

**Issue by jordimarimon** [syntax-tree/mdast-util-to-markdown#39]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.2.0

### Steps to reproduce

When a user defines custom handlers, the extensions defined handlers get erased.

The following example uses the `gfmToMarkdown` extension which defines some handlers.

I also defined a custom handler. Because I have defined a custom handler, all extension handlers will get erased.

```js
import { toMarkdown } from 'mdast-util-to-markdown';
import { gfmToMarkdown } from 'mdast-util-gfm';

// Imagine this is a function that generates a mdast
const tree = makeTree();

const markdown = toMarkdown(tree, {
    extensions: [gfmToMarkdown()],
    handlers: {
       // Custom handler for adding text without escaping
       literal: (node, _parent, _context) => node.value || '',
    },
 });
```

By looking at the source code of `mdast-util-to-markdown`, in the file [`configure.js`](https://github.com/syntax-tree/mdast-util-to-markdown/blob/main/lib/configure.js#L31), I see the following lines:

```js
for (key in extension) {
    if (key === 'extensions') {
      // Empty.
    } else if (key === 'unsafe' || key === 'join') {
      /* c8 ignore next 2 */
      // @ts-expect-error: hush.
      base[key] = [...(base[key] || []), ...(extension[key] || [])]
    } else if (key === 'handlers') {
      base[key] = Object.assign(base[key], extension[key] || {})
    } else {
      // @ts-expect-error: hush.
      base.options[key] = extension[key]
    }
  }
```

`Object.assign(base[key], extension[key] || {})` is erasing the extension handlers.

### Expected behavior

I would expect user defined handlers to be merged with extension defined handlers and only override those that have the same type name.

### Actual behavior

All extension handlers get erased and this breaks the extension.

### Runtime

Node v16

### Package manager

npm v7

### OS

Linux

**Comment by jordimarimon** [comment]
As a workaround, I have done the following which works but it's not pretty:

```js
    // It's an array of extensions
    // See: https://github.com/syntax-tree/mdast-util-gfm/blob/main/index.js#L36
    const {extensions} = gfmToMarkdown();
    const handlers = extensions
        .map(extension => extension.handlers)
        .reduce((acc, curr) => ({...acc, ...curr}), {});

    const markdown = toMarkdown(root(tree), {

        // Needed so we can have support for creating table nodes and inlineCode nodes
        // See: https://github.com/syntax-tree/mdast#gfm
        extensions,

        handlers: {
            // We want to be able to write literal text without escaping it for the descriptions
            literal: (node, _parent, _context) => node.value || '',
            
            // extension handlers
            ...handlers,
        },
    });
```

**Comment by wooorm** [comment]
Looks like you found a bug, can you help to fix it?

**Comment by jordimarimon** [comment]
I will create a PR during the day to provide a fix!

**Comment by jordimarimon** [comment]
There is nothing wrong. I'm closing the issue.
