### ISSUE TITLE
`break` is not handled correctly

### ISSUE THREAD

**Issue by JounQin** [syntax-tree/mdast-util-to-markdown#45]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-to-markdown@1.2.3

### Steps to reproduce

```js
// example.mjs
import { toMarkdown } from 'mdast-util-to-markdown'

const tree = {
  type: 'root',
  children: [
    {
      type: 'break',
    },
  ],
}

console.log(
  toMarkdown(tree, {
    fences: true,
  }),
)
```

### Expected behavior

Empty line

### Actual behavior

```md
\

```

### Runtime

Node v12

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

esbuild

**Comment by JounQin** [comment]
related https://github.com/syntax-tree/hast-util-to-mdast/issues/66

**Comment by wooorm** [comment]
Why is this case not correct?


```
A\
B
```

Yields:

A\
B

**Comment by JounQin** [comment]
> `mdast-util-to-markdown` and `hast-util-to-mdast` do not deal with HTML output though?

That's why raised https://github.com/syntax-tree/hast-util-to-mdast/issues/66

`<p><br></p>` is handled by `hast-util-to-mdast`, it yields `\\\n` in markdown, and will yield `\\\n` in html.

**Comment by wooorm** [comment]
👍

closing, as the behavior here is intentional. The behavior of `hast-util-to-mdast` could be improved though, so let’s continue discussing there: https://github.com/syntax-tree/hast-util-to-mdast/issues/66.
