### ISSUE TITLE
roundtrippping content causes definition to disappear

### ISSUE THREAD

**Issue by ChristianMurphy** [syntax-tree/mdast-util-to-markdown#47]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.2.4

### Link to runnable example

https://stackblitz.com/edit/node-st1b3g?file=index.js

### Steps to reproduce

Run
```js
import { remark as remarFactory } from 'remark';
import { visit } from 'unist-util-visit';

const remark = remarFactory();

// clean extra attributes that make it hard to see issue
function scrubber(tree) {
  visit(tree, function (node) {
    node.value = undefined;
    node.position = undefined;
    node.spread = undefined;
    node.lang = undefined;
    node.identifier = undefined;
    node.label = undefined;
    node.title = undefined;
    node.url = undefined;
  });
}

const content = `[a]: &#xc;`;

const originalAst = remark.parse(content);
const newContent = remark.stringify(originalAst);
const newAst = remark.parse(newContent);

scrubber(originalAst);
scrubber(newAst);

console.log(JSON.stringify(originalAst, null, 4));
console.log(JSON.stringify(newAst, null, 4));
```

result is:

```json
{
    "type": "root",
    "children": [
        {
            "type": "definition"
        }
    ]
}
```

then

```json
{
    "type": "root",
    "children": [
        {
            "type": "paragraph",
            "children": [
                {
                    "type": "text"
                }
            ]
        }
    ]
}
```

and the output text is

```markdown
[a]: 
```

### Expected behavior

definition content is preserved

### Actual behavior

definition content disapepars

### Runtime

Node v16

### Package manager

npm v7

### OS

Linux

**Comment by ChristianMurphy** [comment]
also happens with

```markdown
[a]

[a]: &#xc;
```

**Comment by ChristianMurphy** [comment]
https://spec.commonmark.org/dingus/?text=%5Ba%5D%0A%0A%5Ba%5D%3A%20%26%23xc%3B%0A

**Comment by wooorm** [comment]
[released](https://github.com/syntax-tree/mdast-util-to-markdown/releases/tag/1.2.5)!
