### ISSUE TITLE
Change list item indent from `tab` (size) to `one`

### ISSUE THREAD

**Issue by wooorm** [syntax-tree/mdast-util-to-markdown#48]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

While `one` is used more by authors, historically there have been problems when using it across parsers, hence why the default is `tab`.

### Solution

To illustrate, `one`:

```
1. asd
10. asdasd
100. asdasdasd

* asd
* asdasd
* asdasdasd
```

`tab`:

```
1.  asd
10. asdasd
100.    asdasdasd

*   asd
*   asdasd
*   asdasdasd
```

Note that `tab` is more consistent. Especially around the 1st and 10th mark of incrementally numbered items. And the 100th, 1kth, 10kth items. Whereas `one` will always be staggered. It’s probably most common to have lists between 1-99 items, hence I deem that most important.
This is mostly noticeable when trying to indent further lines: they have to match the items “bullet” `\d+[\.)]\ {1,4}`.

Still, `one` seems to be used more? So probably good to switch the default output format to that?

### Alternatives

stay as is

**Comment by Murderlon** [comment]
From how I've seen people write markdown, I've almost never seen them use `tab`, and I personally always set it to `one` too. That's of course a small sample size but my two cents is that this change makes sense.

**Comment by wooorm** [comment]
yeah, same!
