### ISSUE TITLE
Change `fences` default to `true`

### ISSUE THREAD

**Issue by wooorm** [syntax-tree/mdast-util-to-markdown#49]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Fenced code is (arguably) much better than indented code.

- Indented code and lists interfere
- Indented code does not work in MDX
- Indented code uses 4 spaces, block quotes use a `>` and one space, lists use different “indents”, making markup source code impossible to align, so best to not even try
- fenced code supports language flags, which are super useful
- fenced code supports “meta” (arbitrary stuff), which is while not used much, useful in plugins

Historically fenced code was not supported everywhere. I think we’re now at a point where it’s basically everywhere. Hence this suggestion.

### Solution

default to `fences: true`.

### Alternatives

as is

**Comment by Murderlon** [comment]
Definitely agree with this one.
