### ISSUE TITLE
Add option to not auto replace links

### ISSUE THREAD

**Issue by VityaSchel** [syntax-tree/mdast-util-to-markdown#52]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

It automatically replaces any link-looking phrases to markdown entity for link

### Solution

Add option to not replace them

### Alternatives

No :(((

**Comment by wooorm** [comment]
This project does no such thing.

Please properly fill out the issue template.
