### ISSUE TITLE
 Ampersands in link URLs are erroneously escaped with a \

### ISSUE THREAD

**Issue by drzax** [syntax-tree/mdast-util-to-markdown#53]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-stringify@10.0.2, remark@14.0.2, mdast-util-to-markdown@1.3.0 

### Link to runnable example

https://codesandbox.io/s/late-rgb-4gn6eh

### Steps to reproduce

Run `[Hello world!](https://example.com/?one=1&two=2)` through remark to parse into an AST and re-stringify and you get a different string out the end: `[Hello world!](https://example.com/?one=1\&two=2)`.

### Expected behavior

This should produce output identical to the input.

### Actual behavior

The URL ends has the ampersand escaped with a \

This issue was discussed in #8, which was closed as invalid, however the underscore escaping reported in that issue now appears to be fixed, while the issue with ampersands discussed in the comments remains.

### Runtime

Node v16

### Package manager

npm v7

### OS

macOS

**Comment by wooorm** [comment]
Why? What's the error here?

**Comment by drzax** [comment]
Closing. I misunderstood the CommonMark spec. 

It's also a shame that many markdown->html converters don't handle escaped characters in href attributes, but I guess that's their problem.

**Comment by wooorm** [comment]
> It's also a shame that many markdown->html converters don't handle escaped characters in href attributes

Hmm, in my experience there is a lot of CommonMark and GFM support now?
As these tools apparently don’t support CommonMark/GFM, perhaps you can choose alternative tools?
