### ISSUE TITLE
Roundtripping three empty lists results in a thematic break

### ISSUE THREAD

**Issue by wooorm** [syntax-tree/mdast-util-to-markdown#6]
### Your environment

n/a

### Steps to reproduce

The following uncommon markdown is three empty lists/list items in each other.

```markdown
+ * -
```

### Expected behavior

🤷‍♂️

### Actual behavior

Given that `bullet` is set to a value that can also be used for a thematic break (`-` or `*`), `from-markdown`  will serialize as `* * *` or `- - -`, which is then parsed again as a thematic break.

**Comment by benwoodward** [comment]
What I just experienced is that `---` is serialized as `***`.

## Code:
```javascript
const mdSyntaxTree = markdownToMdAst(markdown);
console.log(toMarkdown(mdSyntaxTree));

function markdownToMdAst(markdown) {
  const mdAstTree = unified()
    .use(remarkParse)
    .parse(markdown)
  return mdAstTree;
}
```

## Input: 

```markdown
one

---

two
```

## Output:
![image](https://user-images.githubusercontent.com/1472981/100923537-31885a80-3544-11eb-86c9-6d3806781b22.png)

**Comment by ChristianMurphy** [comment]
@benwoodward what you're describing is different, unrelated, and expected behavior.
Both are thematic breaks https://astexplorer.net/#/gist/526a859153287c044491fa011ed08a14/c4ae05f5e409472ddf66386f216bf29a0681be4d
MDAST is an [AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree), not a [CST](https://en.wikipedia.org/wiki/Parse_tree).
Meaning it will preserve structure, it was a thematic break before, it still is a thematic break, but it may not preserve the exact formatting as before.

**Comment by ChristianMurphy** [comment]
Another example related to this, lists with a thematic break inside also collapse into just a thematic break

```markdown
- * **
```

**Comment by ChristianMurphy** [comment]
Another variation of this

```markdown
-    -

-
    -    -
```

compiles to

```markdown
*   *

*   *   *
```

which appears to trigger the issue again, even in latest

**Comment by wooorm** [comment]
Could you make this reproducible? Or is it literally this way in this projects tests?
I’m hoping that this was already fixed, because  the tests seem to indicate it: https://github.com/syntax-tree/mdast-util-to-markdown/commit/0148aa6e0318116cf5d2102cd8be28486be9d737.

**Comment by ChristianMurphy** [comment]
https://stackblitz.com/edit/node-dsbc65?file=index.js

**Comment by wooorm** [comment]
thanks! [released too](https://github.com/syntax-tree/mdast-util-to-markdown/releases/tag/1.2.6)!
