### ISSUE TITLE
Cannot round-trip blockquotes with square brackets

### ISSUE THREAD

**Issue by achingbrain** [syntax-tree/mdast-util-to-markdown#61]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-to-markdown@2.1.0

### Steps to reproduce

When trying to use the snazzy new [GitHub Alerts](https://github.com/orgs/community/discussions/16925) extension, `mdast-util-to-markdown` appears to be escaping the opening square bracket when converting the AST back to markdown.

```js
import { fromMarkdown } from 'mdast-util-from-markdown'
import { toMarkdown } from 'mdast-util-to-markdown'

const input = `
Hello world

> [!TIP]
> This is a tip

Very exciting.
`

console.info('--> input')
console.info(input)
console.info('<-- input')

const parsed = fromMarkdown(input)
const output = toMarkdown(parsed)

console.info('--> output')
console.info(output)
console.info('<-- output')
```

The output is:

```
Hello world

> \[!TIP]
> This is a tip

Very exciting.
```

`mdast-util-from-markdown` seems to be reading it ok - if I add this between `fromMarkdown` and `toMarkdown`:

```js
console.info('--> parsed block content')
console.info(parsed.children[1].children[0].children[0].value)
console.info('<-- parsed block content')
```

... I see:

```
--> parsed block content
[!TIP]
This is a tip
<-- parsed block content
```

### Expected behavior

```
--> input

Hello world

> [!TIP]
> This is a tip

Very exciting.

<-- input
--> output
Hello world

> [!TIP]
> This is a tip

Very exciting.

<-- output
```

### Actual behavior

```
--> input

Hello world

> [!TIP]
> This is a tip

Very exciting.

<-- input
--> output
Hello world

> \[!TIP]
> This is a tip

Very exciting.

<-- output
```

### Affected runtime and version

node@20.11.0

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by remcohaszing** [comment]
`toMarkdown` escapes ambiguous characters, such as `[`. The output markdown is equivalent. GitHub understands it fine too.

**Comment by achingbrain** [comment]
Is there an option for it not to do that?  It breaks tooling such as VSCode plugins:

<img width="805" alt="image" src="https://github.com/syntax-tree/mdast-util-to-markdown/assets/665810/e2377a2f-ac0c-46bd-8f0a-c457a00660fd">

vs

<img width="797" alt="image" src="https://github.com/syntax-tree/mdast-util-to-markdown/assets/665810/1df12b34-5e0c-4353-8957-67ca93c1c936">

**Comment by wooorm** [comment]
> It breaks tooling such as VSCode plugins:

If it breaks tools then report with those tools.

---

The `[` has to be escaped because otherwise it could turn into a link based on complex things. Such as:

```markdown
> [!TIP]
> This is a tip

[!tip]: https://example.com
```

This makes a link out of `!TIP`.

---

GH applies this “extension” not as a syntax extension. But later. In the HTML. You can view this exactly by trying what we generate out:

```
> \[!TIP]
> This is a tip
```

> \[!TIP]
> This is a tip

^-- it works fine.

> Is there an option for it not to do that

Yes, there are options to configure the escaping. Please see the readme and look at existing examples of the extensions to see how encoding works.
