### ISSUE TITLE
Incorrect md obtained from bold text with spaces around

### ISSUE THREAD

**Issue by 599316527** [syntax-tree/mdast-util-to-markdown#62]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-to-markdown@2.1.0

### Link to runnable example

https://codesandbox.io/p/sandbox/to-md-bold-text-with-around-spaces-ky39n9

### Steps to reproduce

```js
import { fromMarkdown } from "mdast-util-from-markdown";
import { toMarkdown } from "mdast-util-to-markdown";

const root = fromMarkdown("**A&#32;**");  // -> Strong "A "
const content = toMarkdown(root);          // -> "**A **"
const root2 = fromMarkdown(content);       // -> Text "**A **"
```

### Expected behavior

Escape spaces on edges of bold text. (Bold text `A ` -> `**A&#32;**`)

Or for better visual experience, shift edge spaces out of bold text. (Bold text `A ` -> `**A** `)

### Actual behavior

Spaces are not escaped on edges of bold text

### Affected runtime and version

node@16.20.1

### Affected package manager and version

npm@8.19.4

### Affected OS and version

macOS Ventura 13.6.7

### Build and bundle tools

webpack

**Comment by wooorm** [comment]
Yes! This seems to be https://github.com/orgs/syntax-tree/discussions/60#discussioncomment-2111096.
It would need new features as it can’t be done with the current `safe.js` handling.
Perhaps in the `text` handler, but special to emphasis/strong (and GFM strikethrough/delete).

**Comment by ChristianMurphy** [comment]
Welcome @599316527! 👋 
General advise don't put spaces on the inside edge of emphasis, is is very difficult for a human author to produce themselves or edit.

Non breaking spaces is not the same as a space.
It is possible to serialize this but it's complex https://github.com/orgs/syntax-tree/discussions/60#discussioncomment-2111096

IIRC this effort is part of https://github.com/syntax-tree/mdast-util-to-markdown/issues/12

**Comment by 599316527** [comment]
Em, I just mean `&#32;` here. Sorry for using nbsp to cause ambiguity.

JFYI. My usage scenario is to obtain the data structure from the rich text editor and then convert it to the md ast. In the rich text editor, it is a common operation for users to enter spaces around bold text. I currently manually shift the edge spaces out of bold text to bypass this problem.

**Comment by ChristianMurphy** [comment]
> I currently manually shift the edge spaces out of bold text to bypass this problem.

If the intent is for users to be able to understand and edit the markdown directly.
This would be a good idea to keep doing this. Escape characters, while valid, are confusing to some authors.

**Comment by wooorm** [comment]
> This would be a good idea to keep doing this. Escape characters, while valid, are confusing to some authors.

Yes, I agree with this, knowing that you are making a WYSIWYG editor experience.
If we solve this, your users will see `&#x20;`/`&#32;` a lot and they will probably not like it, perhaps thinking it is a bug.
You’d *still* want to shift that space out yourself?
