### ISSUE TITLE
Unexpected escaping of characters since 2.1.1

### ISSUE THREAD

**Issue by tripodsan** [syntax-tree/mdast-util-to-markdown#65]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-to-markdown@2.1.1

### Steps to reproduce

the changes in `mdast-util-to-markdown@2.1.1` cause unexpected escaping of _normal_ characters, for example:

```
├─8  paragraph[3]
│    ├─0 strong[1]
│    │   └─0 link[3]
│    │       │ url: "https://www.example.com"
│    │       │ title: ""
│    │       ├─0 text "Curves on"
│    │       ├─1 emphasis[1]
│    │       │   └─0 text "the"
│    │       └─2 text " ipad. "
```

generates:

```
      **[Curves o&#x6E;_&#x74;he_ ipad. ](https://www.example.com)**
```

it used to generate:
```
      **[Curves on_the_ ipad. ](https://www.example.com)**
```

another example:

```
├─2 paragraph[1]
│   └─0 emphasis[2]
│       ├─0 text "first"
│       └─1 strong[2]
│           ├─0 text "second"
│           └─1 emphasis[1]
│               └─0 link[1]
│                   │ url: "about:blank"
│                   │ title: "title"
│                   └─0 text "important"
```

generates:
```
_first**secon&#x64;_[important](about:blank "title")_**_
```
before:
```
_first**second_[important](about:blank "title")_**_
```

### Expected behavior

it should not escape characters that are not needed to be escaped.

### Actual behavior

it escapes unexpected characters.

### Affected runtime and version

node v20.18.0

**Comment by wooorm** [comment]
Hi! You note that a change happened in a version. Did you see the release notes / commits that were made? The changes are intentional. There are commits, there is talk, there are tests. Do you have arguments?

**Comment by tripodsan** [comment]
I looked at the changelog but afaiu, the fix should only affect "invalid" mdast trees that would produce whitespace inside formats (eg `_ the _`). but in my examples above, the escaping also happens for the valid cases, like:

```
**[Curves on_the_ ipad. ](https://www.example.com)**
```

**[Curves on_the_ ipad. ](https://www.example.com)**

or 

```
_first**second_[important](about:blank "title")_**_
```

**Comment by wooorm** [comment]
This also indeed touches on “invalidness”. Although it isn’t that: all of this is valid.

Asterisks are different than underscores in markdown. There rules are simpler. They can form emphasis/strong more often, because they are less often used in natural language.  Underscores, in words, as you perhaps know, cannot form emphasis. That is why this escape happens here. That `_` is inside `on` and `the`. take for example: `on_the_ipad`: on_the_ipad. See? The underscores show, no emphasis. Not with `on*the*ipad`: on*the*ipad.

I can recommend two things:
a) use asterisks
b) there’s a space missing in the example, you likely want `on ` instead of `on`

Either is fine?

**Comment by tripodsan** [comment]
ok. thanks for the explanation. probably a good thing to switch to `*` ***everywhere*** :-)
