### ISSUE TITLE
underscores in link urls are escaped

### ISSUE THREAD

**Issue by tripodsan** [syntax-tree/mdast-util-to-markdown#8]
### Subject of the issue

Having a link with an url that contains a `_` will escape it. 

### Steps to reproduce

For example, the following tree:

```
├─38 paragraph[3] (77:1-77:229, 4501-4729)
│   └─0 link[1] (77:163-77:229, 4663-4729)
│       │ title: null
│       │ url: "https://www.youtube.com/channel/UCM1CbBpxRg_-FOutzAXjuLg"
│       └─0 text "Jovely" (77:164-77:170, 4664-4670)
```

will produce this markdown:

```
[Jovely](https://www.youtube.com/channel/UCM1CbBpxRg\_-FOutzAXjuLg)
```

Other examples:

```
[@\_thelustlist\_](https://www.instagram.com/\_thelustlist\_/)
```

Test markdown in github:
- [Jovely](https://www.youtube.com/channel/UCM1CbBpxRg\_-FOutzAXjuLg)
- [@\_thelustlist\_](https://www.instagram.com/\_thelustlist\_/)

### Expected behavior

The `_` in the URL should not be escaped.

### Actual behavior

The `_` in the URL is escaped.

**Comment by tripodsan** [comment]
just realized that the escaping is correct. sorry for the noise.

**Comment by wooorm** [comment]
:+1:

Escaping can be better, but escaping markdown is rather complex, so I don’t easily see how this one would work. The escaping here does not cause any harm, as the escapes in destinations work too.

There was a similar issue recently but I couldn’t find it.

**Comment by tripodsan** [comment]
> so I don’t easily see how this one would work.

right.... I think in the previous remark-parser, it didn't escape the `_` in link urls.

**Comment by wooorm** [comment]
That is correct. But the previous compiler had bugs, and this one has less bugs ;)

**Comment by tripodsan** [comment]
@wooorm there is also escaping of `&`, which is also unexpected.  what is the exact reason to escape anything within the `(` `)` of the link url? (except maybe a `)`) ?

**Comment by wooorm** [comment]
https://github.com/syntax-tree/mdast-util-to-markdown/blob/5fa790ee4cdead2a6c11b6a6f73c59eb0f9ca295/lib/unsafe.js#L40-L41

**Comment by tripodsan** [comment]
maybe treating the link URL as `phrasing` is wrong :-)

**Comment by wooorm** [comment]
Character references and -escapes work in link destinations, it’s intended behavior

**Comment by tripodsan** [comment]
> Character references and -escapes work in link destinations, it’s intended behavior

so you mean that this md:

```
[foo][https://example.com/test&quot;.html]
```

would create a link url with `https://example.com/test".html` when parsed?

**Comment by wooorm** [comment]
yes.

We’re serializing markdown here, so if someone had actually escaped that: 

```md
[foo](https://example.com/test&amp;quot;.html)
[foo](https://example.com/test\&quot;.html)
```

...we need to make sure it roundtrips.
